"""Make the ASAP7 BSIM-CMG models simulatable without HSPICE.

    python3 espice.py <pdk_src> <bsimcmg_src> <out>

ASAP7 ships HSPICE cards only (`level = 72`, BSIM-CMG 107). This writes, under <out>/models:

  bsimcmg/        BSIM-CMG 111.0.0 Verilog-A (UC Berkeley, ECL-2.0, from OpenVAF's
                  integration tests), with the module renamed `bsimcmg` and the thermal
                  terminal made internal, so it is a 4-terminal d g s e device
  cards/7nm_{TT,FF,SS}.pm
                  the ASAP7 cards as `.model <name> bsimcmg type=+-1 ...`; drops what
                  CMG 111 no longer declares (level, version, capmod, coremod, nseg)
  espice/asap7.lib
                  sections tt / ff / ss: `.hdl` the VA (VerA compiles it at first use)
                  plus the corner's cards — `.lib "$ASAP7_ROOT/models/espice/asap7.lib" tt`
  ngspice/asap7.lib
                  the same sections without `.hdl`, for ngspice with
                  `pre_osdi $ASAP7_ROOT/models/osdi/bsimcmg.osdi` (built by the derivation)
"""
import re
import shutil
import sys
from pathlib import Path

DROP = {"level", "version", "capmod", "coremod", "nseg"}
CORNERS = ("TT", "FF", "SS")
NOTE = (
    "// ESPice/ASAP7 adaptation (EDA-Packaged asap7, 2026-10-05): module renamed bsimcmg_va ->\n"
    "// bsimcmg (file stem = module name for VerA/ESPice) and the optional thermal terminal t\n"
    "// made an internal node, so the device has the 4 terminals d g s e of a SPICE MOSFET\n"
    "// card. Self-heating (SHMOD=1, RTH0>0) still works with t on the device's own Rth/Cth.\n"
    "// No other change. ECL-2.0 (notice above) applies to this modified file.\n")


def patch_va(src: Path, dst: Path):
    dst.mkdir(parents=True)
    for f in list(src.glob("bsimcmg*")) + [src / "LICENSE.txt", src / "NOTICE.txt"]:
        shutil.copy(f, dst / f.name)
        (dst / f.name).chmod(0o644)
    va = dst / "bsimcmg.va"
    s = va.read_text()
    old = "module bsimcmg_va(d, g, s, e, t);\n    inout d, g, s, e, t;"
    assert old in s, "BSIM-CMG source changed: port list not found"
    s = s.replace(old, "module bsimcmg(d, g, s, e);\n    inout d, g, s, e;")
    s = s.replace('`include "constants.vams"', NOTE + '`include "constants.vams"', 1)
    va.write_text(s)
    body = dst / "bsimcmg_body.include"
    b = body.read_text()
    i, j = b.index("    if ($port_connected(t) == 1) begin"), b.index("    // N or p-type")
    body.write_text(b[:i] + "    // (ESPice/ASAP7: t is internal; its $port_connected warning removed)\n\n"
                    + b[j:])


def convert(pm: Path, dst: Path):
    out = []
    for ln in pm.read_text().splitlines(keepends=True):
        m = re.match(r"\.model\s+(\S+)\s+([np])mos\b", ln, re.I)
        if m:
            out.append(f".model {m.group(1)} bsimcmg type={1 if m.group(2).lower() == 'n' else -1}\n")
        elif ln.startswith("+"):
            kept = [f"{k}={v}" for k, v in re.findall(r"(\w+)\s*=\s*(\S+)", ln)
                    if k.lower() not in DROP]
            out.append(("+ " + " ".join(kept) + "\n") if kept else "")
        else:
            out.append(ln)
    dst.write_text("".join(out))


def lib(path: Path, cards: Path, hdl: Path = None):
    path.parent.mkdir(parents=True)
    text = "* ASAP7 r1p7 BSIM-CMG corners (generated by EDA-Packaged nix/asap7/espice.py)\n"
    for c in CORNERS:
        text += f".lib {c.lower()}\n" + (f'.hdl "{hdl}"\n' if hdl else "") + \
            f'.include "{cards / f"7nm_{c}.pm"}"\n.endl {c.lower()}\n\n'
    path.write_text(text)


def main(pdk: Path, cmg: Path, out: Path):
    models = out / "models"
    patch_va(cmg, models / "bsimcmg")
    (models / "cards").mkdir()
    for c in CORNERS:
        convert(pdk / "models" / "hspice" / f"7nm_{c}.pm", models / "cards" / f"7nm_{c}.pm")
    lib(models / "espice" / "asap7.lib", models / "cards", models / "bsimcmg" / "bsimcmg.va")
    lib(models / "ngspice" / "asap7.lib", models / "cards")


if __name__ == "__main__":
    main(*map(Path, sys.argv[1:4]))
